### ISSUE TITLE
Failed to clean existing content for temp file provider of type temp

### ISSUE THREAD

**Issue by 784134748** [Alfresco/alfresco-keycloak-deployment#12]
08:43:47,916 INFO  [org.jboss.vfs] (MSC service thread 1-2) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this

**Comment by 784134748** [comment]
AND
09:21:12,372 WARN  [org.keycloak.events] (default task-9) type=LOGIN_ERROR, realmId=master, clientId=null, userId=null, ipAddress=60.169.24.2, error=ssl_required

**Comment by rgauss** [comment]
Given that there's absolutely no context given here, I'm guessing you're just reporting things you're seeing in the log that concern you?

These are INFO and WARN level entries and don't necessarily indicate that anything unexpected has occurred.

**Comment by dbraun1991** [comment]
Hi there,
I had the same issue some days shortly and needed 2 days to fix it.

The problem (for me) was a forced passwort reset (I din't consider to be serious) which lead to the fact that the "docker-compose myfile.yml up" could not copy files form the hard drive into the container.
Docker did not recognize the changed password. 

--> The Key was to unmount & mount the disk in the settings.

In case this did not help, my way of troubleshooting:
(1) Does the keycloak-container run anyway?
    --> NO ... probably a different problem
    --> YES --> (2)
(2) Can you reach the (local) keycloak via [browser](https://www.keycloak.org/docs/3.3/server_admin/topics/admin-console.html) ?
    --> NO ... probably a different problem
    --> YES --> (3)
(3) Is there your personal environment?
    --> NO ... probably a different problem
    --> YES --> ONLY the default "master"environment --> (4)
(4) Now its pretty likely that its not about your keycloak (-docker-container-) image, but more about your readWrite-permissions.

I hope that helped and I might save someone else another 2 days    ;-)

**Comment by rgauss** [comment]
This entire Git repo should be considered deprecated.

Please see https://github.com/Alfresco/alfresco-identity-service.
